# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6c7a70c7488d861d9e793031263cc92b7d8458de1da8688b5fa01a5e3b85627148ca5f583df8b9fb581919eacb37ec95829a8a5bbe1ba40757a892018e674a3

test:
  secret_key_base: 18e2202fb44b692f9b9a82c26449f55c8dd76ccc3adbe8275a3e3f39cea673ce7174f0d0d4da93d537aeb4bbf845a20ae1a5b5673c0463bfc2ab65142f76a885

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
